import { HouseModel } from '../types/house';

const sampleHouse: HouseModel = {
  id: 'house-001',
  name: 'Oakwood Residence',
  storeys: 2,
  roofType: 'gable',
  roofPitch: 30,
  rooms: [
    {
      id: 'room-living',
      name: 'Living Room',
      floor: 0,
      x: 0,
      y: 0,
      width: 7,
      depth: 5,
      ceilingHeight: 2.7,
      color: '#e8f4f8',
      doors: [
        {
          id: 'door-living-kitchen',
          wallSide: 'east',
          offset: 1.5,
          width: 0.9,
          swingInward: true,
        },
        {
          id: 'door-living-front',
          wallSide: 'south',
          offset: 2.5,
          width: 1.0,
          swingInward: false,
        },
      ],
      windows: [
        { id: 'win-living-s1', wallSide: 'south', offset: 0.8, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'win-living-s2', wallSide: 'south', offset: 4.5, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'win-living-w1', wallSide: 'west', offset: 1.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
    },
    {
      id: 'room-kitchen',
      name: 'Kitchen',
      floor: 0,
      x: 7,
      y: 0,
      width: 4,
      depth: 5,
      ceilingHeight: 2.7,
      color: '#fdf6e3',
      doors: [
        {
          id: 'door-kitchen-hall',
          wallSide: 'east',
          offset: 1.0,
          width: 0.9,
          swingInward: true,
        },
      ],
      windows: [
        { id: 'win-kitchen-s', wallSide: 'south', offset: 1.0, width: 1.2, height: 1.2, sillHeight: 0.9 },
        { id: 'win-kitchen-n', wallSide: 'north', offset: 1.0, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
    },
    {
      id: 'room-hall',
      name: 'Hallway',
      floor: 0,
      x: 11,
      y: 0,
      width: 2.5,
      depth: 5,
      ceilingHeight: 2.7,
      color: '#f5f5f0',
      doors: [
        {
          id: 'door-hall-dining',
          wallSide: 'east',
          offset: 1.0,
          width: 0.9,
          swingInward: true,
        },
      ],
      windows: [],
    },
    {
      id: 'room-dining',
      name: 'Dining Room',
      floor: 0,
      x: 13.5,
      y: 0,
      width: 4.5,
      depth: 5,
      ceilingHeight: 2.7,
      color: '#fef9f0',
      doors: [],
      windows: [
        { id: 'win-dining-s', wallSide: 'south', offset: 1.0, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'win-dining-e', wallSide: 'east', offset: 1.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
    },
    // Upper floor
    {
      id: 'room-master',
      name: 'Master Bedroom',
      floor: 1,
      x: 0,
      y: 0,
      width: 6,
      depth: 5,
      ceilingHeight: 2.4,
      color: '#eef2ff',
      doors: [
        {
          id: 'door-master-landing',
          wallSide: 'east',
          offset: 1.5,
          width: 0.9,
          swingInward: true,
        },
      ],
      windows: [
        { id: 'win-master-s1', wallSide: 'south', offset: 1.0, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'win-master-s2', wallSide: 'south', offset: 3.5, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'win-master-w', wallSide: 'west', offset: 1.5, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
    },
    {
      id: 'room-bedroom2',
      name: 'Bedroom 2',
      floor: 1,
      x: 6,
      y: 0,
      width: 4.5,
      depth: 5,
      ceilingHeight: 2.4,
      color: '#f0fdf4',
      doors: [
        {
          id: 'door-bed2-landing',
          wallSide: 'east',
          offset: 1.0,
          width: 0.9,
          swingInward: true,
        },
      ],
      windows: [
        { id: 'win-bed2-s', wallSide: 'south', offset: 1.2, width: 1.4, height: 1.2, sillHeight: 0.9 },
        { id: 'win-bed2-n', wallSide: 'north', offset: 1.2, width: 1.2, height: 1.2, sillHeight: 0.9 },
      ],
    },
    {
      id: 'room-bathroom',
      name: 'Bathroom',
      floor: 1,
      x: 10.5,
      y: 0,
      width: 3,
      depth: 3,
      ceilingHeight: 2.4,
      color: '#f0faff',
      doors: [
        {
          id: 'door-bath-landing',
          wallSide: 'east',
          offset: 0.5,
          width: 0.8,
          swingInward: true,
        },
      ],
      windows: [
        { id: 'win-bath-n', wallSide: 'north', offset: 1.0, width: 0.6, height: 0.6, sillHeight: 1.5 },
      ],
    },
    {
      id: 'room-landing',
      name: 'Landing',
      floor: 1,
      x: 10.5,
      y: 3,
      width: 7.5,
      depth: 2,
      ceilingHeight: 2.4,
      color: '#fafafa',
      doors: [],
      windows: [],
    },
  ],
  createdAt: '2026-05-04T00:00:00Z',
  updatedAt: '2026-05-04T00:00:00Z',
};

export default sampleHouse;
